wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.16.4
    framework: huggingface
    huggingface_version: 4.38.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1713525329.0
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 31
      - 49
      - 51
      - 53
      - 55
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 31
      - 49
      - 51
      - 53
      - 55
      3:
      - 2
      - 13
      - 16
      - 17
      - 23
      - 37
      4: 3.11.7
      5: 0.16.4
      6: 4.38.2
      8:
      - 1
      - 3
      - 5
      10:
      - 3
      13: windows-amd64
